/* Generated By:JavaCC: Do not edit this line. EG1Constants.java */
package application;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
@SuppressWarnings("all")
public interface EG1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int create = 5;
  /** RegularExpression Id. */
  int object = 6;
  /** RegularExpression Id. */
  int TIPO = 7;
  /** RegularExpression Id. */
  int NUMERO = 8;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 9;
  /** RegularExpression Id. */
  int CADENA = 10;
  /** RegularExpression Id. */
  int INITSIMBOL = 11;
  /** RegularExpression Id. */
  int FINSIMBOL = 12;
  /** RegularExpression Id. */
  int FLINEA = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"CREATE\"",
    "\"OBJECT\"",
    "<TIPO>",
    "<NUMERO>",
    "<IDENTIFICADOR>",
    "<CADENA>",
    "\"(\"",
    "\")\"",
    "\";\"",
  };

}
