/* Generated By:JavaCC: Do not edit this line. EG1Constants.java */
package application;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
@SuppressWarnings("all")
public interface EG1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int create = 5;
  /** RegularExpression Id. */
  int object = 6;
  /** RegularExpression Id. */
  int insert = 7;
  /** RegularExpression Id. */
  int select = 8;
  /** RegularExpression Id. */
  int from = 9;
  /** RegularExpression Id. */
  int TYPE = 10;
  /** RegularExpression Id. */
  int NUMBER = 11;
  /** RegularExpression Id. */
  int IDENTIFIER = 12;
  /** RegularExpression Id. */
  int STRING = 13;
  /** RegularExpression Id. */
  int INITSIMBOL = 14;
  /** RegularExpression Id. */
  int ENDSIMBOL = 15;
  /** RegularExpression Id. */
  int ENDLINE = 16;
  /** RegularExpression Id. */
  int COMMA = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"CREATE\"",
    "\"OBJECT\"",
    "\"INSERT\"",
    "\"SELECT\"",
    "\"FROM\"",
    "<TYPE>",
    "<NUMBER>",
    "<IDENTIFIER>",
    "<STRING>",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\",\"",
  };

}
